// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByE4bpFCOkQySBlI7n_JQ0kYt-oSt31PU',
    appId: '1:18163605615:web:3181d4ebb28b88f7d6ad9a',
    messagingSenderId: '18163605615',
    projectId: 'agromarket-625b2',
    authDomain: 'agromarket-625b2.firebaseapp.com',
    storageBucket: 'agromarket-625b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByE4bpFCOkQySBlI7n_JQ0kYt-oSt31PU',
    appId: '1:18163605615:android:3181d4ebb28b88f7d6ad9a',
    messagingSenderId: '18163605615',
    projectId: 'agromarket-625b2',
    storageBucket: 'agromarket-625b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByE4bpFCOkQySBlI7n_JQ0kYt-oSt31PU',
    appId: '1:18163605615:ios:3181d4ebb28b88f7d6ad9a',
    messagingSenderId: '18163605615',
    projectId: 'agromarket-625b2',
    authDomain: 'agromarket-625b2.firebaseapp.com',
    storageBucket: 'agromarket-625b2.firebasestorage.app',
    iosBundleId: 'com.example.agromarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByE4bpFCOkQySBlI7n_JQ0kYt-oSt31PU',
    appId: '1:18163605615:ios:3181d4ebb28b88f7d6ad9a',
    messagingSenderId: '18163605615',
    projectId: 'agromarket-625b2',
    authDomain: 'agromarket-625b2.firebaseapp.com',
    storageBucket: 'agromarket-625b2.firebasestorage.app',
    iosBundleId: 'com.example.agromarket',
  );
}